[tool.poetry]
name = "pyloremGen"
version = "2.0.0"
description = "A Python library for generating Lorem Ipsum text."
authors = ["Vitório Augusto Cavalheiro"]
license = "MIT"
homepage = "https://github.com/oVitorio-ac/pyloremGen/"
repository = "https://github.com/oVitorio-ac/pyloremGen/"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
reportlab = "4.2.*"

[tool.poetry.group.dev.dependencies]
black = "24.4.*"
isort = "*"
detect-secrets = "1.5.0"

[tool.black]
line-length = 100
target-version = ['py38']
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
