name: Delete merged branch

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true && !contains(fromJSON('["development", "main", "master"]'), github.head_ref)
    runs-on: ubuntu-latest
    steps:
    - name: Delete merged branch
      run: gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
